<add new file create_table,input_data and new app,py>
BeckyHung37/taipei-day-trip-website pull request #2
Opened 2021-04-26 17:27 UTC by BeckyHung37

洪姍琪
http://54.179.121.192:3000/api/attractions?page=1

2021-04-26 17:31 UTC, cwpeng requested changes
測試的網址無法正常運作哦 ~

2021-04-27 00:17 UTC, BeckyHung37 commented
了解！！謝謝老師><我修改一下

2021-04-27 12:33 UTC, BeckyHung37 commented
老師～我已修改完畢，再麻煩您確認一次，謝謝老師！

2021-04-27 13:15 UTC, cwpeng requested changes
關鍵字的部份沒辦法正常運作：
http://54.179.121.192:3000/api/attractions?page=1&keyword=臺北
單一景點的部份也是：
http://54.179.121.192:3000/api/attraction/13

2021-04-27 14:47 UTC, BeckyHung37 commented
好的，謝謝老師！！
已修改完畢，再請老師過目，感謝

2021-04-27 15:02 UTC, cwpeng approved these changes
Finally, Good. :)
Keep Going. ~~~~~~~

2021-04-27 15:12 UTC, BeckyHung37 commented
謝謝老師><太好了～～終於！！！！

2021-04-27 15:37 UTC, cwpeng commented
記得 Merge Pull Request 哦 ~

2021-04-27 16:06 UTC, BeckyHung37 commented
阿阿～老師不好意思我程式碼的部分有小修改，我會先關掉這個然後重發一次pull request review給老師><謝謝老師

2021-04-27 16:25 UTC, BeckyHung37 commented
老師我發現上傳檔案後可以直接merge不用再請老師review~太好了～～

2021-04-27 16:25 UTC, merged